import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import io from "socket.io-client";
let socket;
import ArticleCard from "../components/ArticleCard";
import Timeago from "react-timeago";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export const getServerSideProps = async () => {
  const articles = await prisma.articles.findMany({
    orderBy: [
      {
        date: "desc"
      }
    ]
  });
  return {
    props: {
      initialArticles: articles
    }
  };
};

export default function Home({ setHeader, initialArticles }) {
  const parsedArticleCards = initialArticles.map((article) => {
    console.log(article);
    return (
      <ArticleCard
        key={article.id}
        id={article.id}
        title={article.title}
        body={article.body.slice(0, 100) + "..."}
        date={<Timeago date={article.date} />}
        image={article.image}
      />
    );
  });

  useEffect(() => {
    setHeader({ header: "NEWS FEED", hidden: false });
  }, []);

  // useEffect(() => socketInitializer(), []);

  // const socketInitializer = async () => {
  //   await fetch("/api/socket");
  //   socket = io();

  //   socket.on("connect", () => {
  //     console.log("connected");
  //   });

  //   socket.on("update-input", msg => {
  //     setInput(msg);
  //     console.log("changed");
  //   });
  // };

  // const onChangeHandler = e => {
  //   setInput(e.target.value);
  //   socket.emit("input-change", e.target.value);
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{parsedArticleCards}</div>
    </div>
  );
}
